name: prometheus

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"


#      - name: Make application.yml
#        run: |
#          mkdir -p src/main/resources
#          echo "${{ secrets.APPLICATION }}" > src/main/resources/application-dev.yml

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker BUILD_PUSH
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_REPO }}


      - name: Deploy_EC2
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            cd /home/monitor  ㅎ
            sudo docker-compose down || true
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            sudo docker-compose up -d
            sudo docker image prune -f
      

